name: Cargo Build & Test

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    strategy:
      matrix:
        settings:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          - platform: "windows-latest"
    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: scanner-${{ github.sha }}-${{ matrix.settings.platform }}
          path: target
